language: python
python:
- '3.6'
addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev
install:
  - sudo apt-get update
  - wget "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.1-cp36-cp36m-linux_x86_64.whl"
  - pip install wxPython-4.0.1-cp36-cp36m-linux_x86_64.whl
  - pip install -r requirements.txt
script:
  - pytest

